import { resolve } from "pathe";
import { writeFile } from "node:fs/promises";
import { ensureDir } from "../../utils/fs.js";
import { createScopedLogger } from "../../utils/logger.js";
import type { ExtractionResult } from "../../types/extraction.js";

const log = createScopedLogger("sveltekit-scaffolder");

export async function scaffoldSvelteKit(
  outputDir: string,
  extraction: ExtractionResult
): Promise<void> {
  log.info(`Scaffolding SvelteKit project at ${outputDir}`);

  // Create directory structure
  const dirs = [
    "src/lib",
    "src/lib/components",
    "src/lib/styles",
    "src/lib/assets",
    "src/routes",
    "static",
  ];

  for (const dir of dirs) {
    await ensureDir(resolve(outputDir, dir));
  }

  // package.json
  await writeFile(
    resolve(outputDir, "package.json"),
    JSON.stringify(
      {
        name: "cloned-site",
        version: "0.0.1",
        private: true,
        type: "module",
        scripts: {
          dev: "vite dev",
          build: "vite build",
          preview: "vite preview",
        },
        devDependencies: {
          "@sveltejs/adapter-auto": "^4.0.0",
          "@sveltejs/kit": "^2.16.0",
          "@sveltejs/vite-plugin-svelte": "^5.0.0",
          svelte: "^5.0.0",
          vite: "^6.0.0",
        },
      },
      null,
      2
    ),
    "utf-8"
  );

  // svelte.config.js
  await writeFile(
    resolve(outputDir, "svelte.config.js"),
    `import adapter from '@sveltejs/adapter-auto';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    adapter: adapter(),
  },
};

export default config;
`,
    "utf-8"
  );

  // vite.config.ts
  await writeFile(
    resolve(outputDir, "vite.config.ts"),
    `import { sveltekit } from '@sveltejs/kit/vite';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [sveltekit()],
});
`,
    "utf-8"
  );

  // app.html
  await writeFile(
    resolve(outputDir, "src/app.html"),
    `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%sveltekit.assets%/favicon.png" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    %sveltekit.head%
  </head>
  <body data-sveltekit-prerender="true">
    <div style="display: contents">%sveltekit.body%</div>
  </body>
</html>
`,
    "utf-8"
  );

  // +layout.svelte
  await writeFile(
    resolve(outputDir, "src/routes/+layout.svelte"),
    `<script>
  import '../lib/styles/tokens.css';
  let { children } = $props();
</script>

{@render children()}
`,
    "utf-8"
  );

  // Placeholder +page.svelte
  await writeFile(
    resolve(outputDir, "src/routes/+page.svelte"),
    `<script>
  // Components will be generated by AI from extraction data
</script>

<main>
  <p>Clone placeholder — components to be generated</p>
</main>
`,
    "utf-8"
  );

  log.success("SvelteKit project scaffolded");
}
